-- CreateTable
CREATE TABLE "Company"
(
    "id"        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"      TEXT        NOT NULL,
    "slugUrl"   TEXT        NOT NULL,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL
);

CREATE UNIQUE INDEX "Company_slugUrl_key" ON "Company"("slugUrl");